### ISSUE TITLE
Pypi installation fail.

### ISSUE THREAD

**Issue by uetoyo** [PySide/PySide#128]
File "C:\Users\{user}\AppData\Local\Temp\pip-build-3iy1pet1\pyside\popenasync.py", line 26, in <module>
        if subprocess.mswindows:
    AttributeError: module 'subprocess' has no attribute 'mswindows'

Win7 OS; Python 3.5

**Comment by MrLeeh** [comment]
I get the same error on Mac OS X 10.10.5 with python3.5:

```
Collecting pyside
  Downloading PySide-1.2.2.tar.gz (9.3MB)
    100% |████████████████████████████████| 9.3MB 42kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/8_/4r055br17k9_g6_0dlck12tc0000gn/T/pip-build-7k7jhzah/pyside/setup.py", line 89, in <module>
        from utils import rmtree
      File "/private/var/folders/8_/4r055br17k9_g6_0dlck12tc0000gn/T/pip-build-7k7jhzah/pyside/utils.py", line 10, in <module>
        import popenasync
      File "/private/var/folders/8_/4r055br17k9_g6_0dlck12tc0000gn/T/pip-build-7k7jhzah/pyside/popenasync.py", line 26, in <module>
        if subprocess.mswindows:
    AttributeError: module 'subprocess' has no attribute 'mswindows'

``

**Comment by ctismer** [comment]
This has been fixed, see the latest commit history.
Update to the latest revision and build with `--ignore-git`, otherwise you
always get the old 1.2.2 version. 1.2.3 has not yet been tagged.

**Comment by cchriste** [comment]
I'm getting the same error with 1.2.4 installed from pip. :(

**Comment by fredrikaverpil** [comment]
Pyside is very old by now. You can install the latest version via `pip install pyside6`.
